import os

"""
1.DEFINIR PASTA ONDE ELE VAI TRABALHAR
2.FAZER A BUSCA E FILTRO DAS PASTAS QUE CONTENHAM "EXCLUIR_" NO NOME
3.ADICIONAR NUMA LISTA ESSES NOMES DE PASTAS
4.REMOVER OS ITENS
5.ADICIONAR NUM ARQUIVO DE LOG PARA ARMAZENAR OS NOMES DOS ITENS EXCLUIDOS
6.REMOVER DO SITES-ENABLE E DAR UM REFRESH NO APACHE2
"""
"""DECLARAÇÃO DAS VARIAVEIS"""
caminho_pastas = '/var/www/'

def limpar_pastas():
    excluir_itens = os.listdir(caminho_pastas)
    print(excluir_itens)
limpar_pastas()

